- .prettierrc
- .vscode/settings.json
- content/docs/builtin-middleware/_index.md
- content/docs/builtin-middleware/bearer-auth.md
- themes/hugo-book/assets/_custom.scss
Finally I was able to find time to start the documentation! I hope to be able to get all of the middleware and some of the things in the main repo documented as well!
I started with the Bearer Auth middleware, and a styling update to fix word wrapping. Please let me know what you think of my changes with the options descriptions, and the recipe section.
Also please let me know how I should format these pull requests in the future, maybe we can make a template if it makes sense 😄
> docs(bearer-auth): add description for options, recipe for Fastly Compute@Edge

- content/docs/builtin-middleware/validator.md
This PR adds documentation for the new `validator` middleware array support, as well as updates the description of the `validator` middleware.
> docs(validator): update description, add info about array support

- content/docs/api/context.md
This PR provides more accurate examples of body parsing as of v2.1.0, as noted in https://github.com/honojs/hono/issues/588
> docs(context): update examples of body parsing as of v2.1.0

- config.toml
- themes/hugo-book/layouts/partials/docs/search.html
This PR introduces FlexSearch as mentioned in #19
> feat(search): enable search, fix search text

- api/hono.md
> docs(api): fix strict mode section

- concepts/philosophy.md
- index.md
Your framework looks really compelling and I've spent quite a bit of time reading the docs. I noticed a few places where phrasing and grammar felt unclear. This PR makes a few tiny changes to the ways certain words are used, as well as rewriting several phrases to improve clarity.
If there is interest, I'd be glad to work through the docs to improve readability and clarity – please let me know if you would be open to that!
> Improve phrasing and grammar

- api/context.md
> fix duplicated backquote

- api/context.md
- api/exception.md
- api/hono.md
- api/request.md
What started with `comming` -> `coming` grew slightly larger. Will review other parts incrementally.
> chore: improvements to the documentation

- getting-started/basic.md
- add new templates(aws-lambda, vercel).
- unify command syntax
> Update command syntax

- .vitepress/theme/NotFound.vue
- .vitepress/theme/index.js
Fix #68 . This is a work around.
> fix: add custom not found

- api/routing.md
Fix https://github.com/honojs/hono/issues/1255
> fix hostname-routing

- middleware/third-party.md
Valibot should also be added to the list.
Thanks!
> docs: add valibot validator to 3rd-party middleware page

- middleware/builtin/cookie.md
Changes to docs related to https://github.com/honojs/hono/pull/1279
> Docs for cookie signing

- getting-started/aws-lambda.md
Ref: https://github.com/honojs/hono/pull/1305
> docs(aws-lambda): Adding Usage `c.env.requestContext`

- middleware/builtin/cookie.md
> fix typo in middleware/builtin/cookie.md

- .gitignore
- middleware/builtin/secure-headers.md
To match recent updates from https://github.com/honojs/hono/pull/1395
> update secure headers middleware docs

- getting-started/basic.md
This PR will include documentation improvement. It will fix grammar errors, sentence structure and overall flow of the doc.
> Improve Hono documentation

- middleware/builtin/logger.md
This pull request updates the documentation for the Logger Middleware. It includes improved explanations of the middleware's functionality and usage, and on customizing the logging behavior using the `PrintFunc` function.
- Enhanced the documentation for the Logger Middleware.
- Added explanations about the `PrintFunc` function.
- Provided examples of how to pass and use a custom logging function.
Closes: #86
> docs: Add details of log output and define the PrintFunc

- .vitepress/config.js
- helpers/jwt.md
- utilities/jwt.md
This pull request adds comprehensive documentation for the util/jwt module. 
The JWT docs includes information on:
- Import
- Sign
- Verify
- Decode
- Payload Validation
- Custom Error Types
- Supported AlgorithmTypes
> docs: Add Jwt Utility 

- getting-started/deno.md
Added information about the update to deno deploy supporting npm.
closes #100
> docs: Add deno deploy update

- middleware/builtin/compress.md
Added note how this middleware is not available in bun since it does not yet support `CompressionStream`
> docs: Update note for bun users

- helpers/testing.md
Url currently points to localhost
> Fix url typo

- .vitepress/config.js
- helpers/streaming.md
- index.md
I've added detailed documentation for the "streaming Helper" which provides a method to extend c.stream. 
Ref: https://github.com/honojs/hono/pull/1504
> docs(helper): streaming-sse

- api/request.md
Hi, @yusukebe 
This doc is a preparation for Hono v3.8
> docs(HonoRequest): add parseBody behavior description

- guides/testing.md
I found an easy way to make POST requests, so I modified the documentation.
> docs: Improve testing guide

- getting-started/lambda-edge.md
Just a simple duplication of `from` statement fix.
> docs: Fixes code in AWS Lambda@Edge callback example

- getting-started/aws-lambda.md
- getting-started/basic.md
- getting-started/cloudflare-pages.md
- getting-started/cloudflare-workers.md
- getting-started/fastly.md
- getting-started/lagon.md
- getting-started/lambda-edge.md
- getting-started/netlify.md
- getting-started/nodejs.md
- getting-started/vercel.md
- guides/validation.md
- index.md
close #135
I havn't executed and verified all commands.
In this docs, commands is not highlighted, `txt` is added instead of `sh`.
> Add yarn, pnpm, and bun for a package manager

- api/context.md
> docs: add description for `ContextVariableMap`

- snippets/grouping-routes-rpc.md
Corrected incorrect reference paths.
> fix: update the references path of RPC snippets

- .vitepress/config.ts
- snippets/with-remix.md
I tried to add Remix + Hono snippets.
> docs: add Remix + Hono snippets as Ecosystem

- getting-started/aws-lambda.md
I would appreciate it if you could enable this feature after the ticket has been merged.
https://github.com/honojs/hono/pull/1625
> Lambda Adaptor: streaming response

- snippets/cloudflare-queue.md
Sorry, I found a typo in my writes...
> docs: typo "queue" to "queues"

- getting-started/aws-lambda.md
- getting-started/lambda-edge.md
- fixed https://github.com/honojs/hono/pull/1710/
- [AWS Lambda adds support for Node.js 20](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-support-node-js-20/)
> Lambda update for v3.11

- helpers/testing.md
- snippets/grouping-routes-rpc.md
- snippets/zod-openapi.md
> docs: remove `jsonT` since it has been deprecated

- middleware/builtin/jwt.md
> docs: add tips to use jwt helper with dynamic secret

- getting-started/others.md
Netlify already has a page on the website, this commit removes it from the others list.
> Remove Netlify from the others list as it has an existing page

- helpers/css.md
> fix typo in CSS helper docs

- api/context.md
I add description of `c.body()`.
And I move the common response description in `c.text()` to `c.body()`.
> add `c.body()`

- guides/examples.md
https://github.com/honojs/hono/issues/1572
> docs: add `Can't modify immutable headers.` tips to proxy example

- getting-started/vercel.md
This pull request addresses issue #204 by adding missing information about the Vercel App Router methods.
> Added more API methods for Vercel App Router

- api/hono.md
- getting-started/bun.md
https://github.com/orgs/honojs/discussions/1764
> docs: clarify how to use diff to set port settings

- getting-started/nodejs.md
Added Dockerfile example to Nodejs docs.（ #220 ）
Please point out to me if I am not following Dockerfile best practices.
> docs: added Dockerfile example to Documentation

- .vitepress/config.ts
- guides/others.md
> docs: Twitter to X

- api/context.md
- guides/rpc.md
- helpers/html.md
- helpers/ssg.md
- middleware/builtin/jsx-renderer.md
https://github.com/honojs/website/issues/241
> `jsx` and `tsx` syntax for files using JSX

- helpers/ssg.md
> docs: minor typo

- getting-started/nodejs.md
A quick fix to the grammar in the Node.js getting started.
> docs: fix grammar in nodejs getting started

- helpers/streaming.md
https://github.com/honojs/hono/pull/2262
https://github.com/honojs/hono/issues/2164
> docs: add error handling section to streaming helper

- .vitepress/config.ts
- getting-started/others.md
Supabase Edge Functions is confirmed to work.
https://github.com/honojs/website/issues/256
> Remove others.md

- getting-started/deno.md
create-hono makes a project with main.ts file but the command in the documentation was instructing to run hello.ts
> fix: type in deno.md

- guides/middleware.md
Reference: https://github.com/honojs/hono/issues/2423#issuecomment-2022118020
> docs(guides): Add warning for using different versions middleware

- getting-started/bun.md
- getting-started/cloudflare-workers.md
- getting-started/deno.md
`notFoundOption` should be written as `onNotFound`.
> Update `notFoundOption` to `onNotFound`

- getting-started/cloudflare-workers.md
Add section on deploying Cloudflare Worker via GitHub Action CI.
This is my first documentation contribution, please feel free to point out any errors or things that shouldn't be here, thanks!😊
> docs: update cloudflare worker deploy section

- snippets/cloudflare-queue.md
- snippets/grouping-routes-rpc.md
- snippets/validator-error-handling.md
- snippets/with-remix.md
No changes in the content, fixed some spacing and formatting.
> Format snippets to match code style

- .vitepress/theme/custom.css
> Change code block text color on light theme (#307)

- concepts/routers.md
> Add language type in code block

- helpers/websocket.md
https://github.com/honojs/hono/issues/2535
> docs: add warning alert to websocket helper's docs

- getting-started/cloudflare-workers.md
I've added how to configure local development variables in cloudflare worker to the documentation as well, please let me know if you have any questions.
@yusukebe
> docs: add "cloudflare worker local dev env" section

- guides/middleware.md
Hi @yusukebe,
I added what was mentioned in #317 to the existing custom middleware section in the guide. I tried to keep it short but informative. I was debating adding another example for adding parameters to custom middleware, but I figured linking to the `createMiddleware` factory would give a user the answer they are looking for.
Let me know if you want any updates or changes!
closes: #317
> Added docs for creating middleware

- .vitepress/theme/custom.css
- index.md
Hi @yusukebe 
I was sad that I couldn't see the kawaii logo when I activated kawaii mode on mobile, so I made it visible.
> feat: kawaii mode for mobile

- getting-started/bun.md
> docs(bun): typo

- middleware/third-party.md
- Added [Hono Rate Limiter](https://github.com/rhinobase/hono-rate-limiter) in the docs
> docs(middleware): added hono-rate-limiter

- helpers/dev.md
This change shows how the options object can be added (without it, this page doesn't show how to add the options)
> Dev Helper with Options Object

- getting-started/basic.md
- top.md
I have updated hono-create commands for top.md and getting-started/basic.md
> docs: update hono-create commands

- api/request.md
In sync with https://github.com/honojs/hono/pull/2841
> docs(request): add `blob()` and `formData()`

- getting-started/supabase-functions.md
- Use `jsr:` specifier
- Remove unused types
> docs: update supabase-functions

- guides/rpc.md
Closes [@honojs/hono#2270](https://github.com/honojs/hono/issues/2270)
> docs: add tip in RPC

- getting-started/bun.md
Add Bun install on an existing project with `bun install` command as an additional step.
> feat: add Bun install on existing project

- docs/middleware/builtin/jwt.md
> Update JWT Middleware

- docs/api/routing.md
Closes https://github.com/honojs/hono/issues/29822982
> fix `getPath()`

- docs/concepts/benchmarks.md
Minor adjustment of phrasing to make it the same as the example above.
> Phrasing correction in benchmarks.md

- docs/getting-started/cloudflare-pages.md
I will also go through and submit a PR for Cloudflare to get the docs up to date.
Closes #407
> Add section for deployment with Cloudflare dashboard

- docs/getting-started/cloudflare-workers.md
> fixed typo

- docs/middleware/third-party.md
Add Effect Schema Validator link.
> Update third-party.md: add Effect Schema Validator link

- docs/guides/middleware.md
confer https://github.com/honojs/website/pull/451#issuecomment-2241881464
> docs(middleware): add example for accessing context inside middleware arguments

- examples/pylon.md
Hi, I relaunched the website of [Pylon](https://pylon.cronit.io) and therefore I had to change the documentation links.
> docs: update pylon.md

- docs/api/context.md
close https://github.com/honojs/hono/issues/585
close https://github.com/honojs/hono/issues/896
close https://github.com/honojs/hono/issues/2484
> docs(context): clarify usage of `c.set` and `c.get`

- examples/pylon.md
Hey @yusukebe.
I want to add a disclaimer to figure out if the bun requirement of pylon is a dealbreaker for the community.
I am already working on a solution to support the same runtimes as Hono.
I just want to validate this feature. Could you share your personal opinion on this matter?
> docs(pylon.md): add bun requirement disclaimer

- docs/guides/validation.md
added warning about header name case.
ref: https://github.com/honojs/hono/issues/3416#issuecomment-2354669238
I'm considering adding a few more reasons for this behavior.
> Add warning about validating headers in validation.md

- examples/pylon.md
Hi!
I just release Pylon v2. Due to some breaking changes I need to adapt the docs.
- Docs: https://pylon.cronit.io/docs/getting-started
- Release notes: https://pylon.cronit.io/docs/release-notes/v2.0
- Migration guide: https://pylon.cronit.io/docs/release-notes/migrating-from-v1-to-v2
> docs(pylon.mdx): update to pylon v2

- docs/middleware/builtin/secure-headers.md
Added the `contentSecurityPolicyReportOnly` option.
> docs(secure-headers): add `contentSecurityPolicyReportOnly`

- docs/helpers/streaming.md
Closes https://github.com/honojs/hono/issues/3449
> docs(streaming): add description for `Content-Encoding: 'Identity'` header

- docs/guides/rpc.md
Ref: https://github.com/honojs/hono/issues/2280
> docs(guides): add "Not Found" in RPC

- docs/index.md
Thank you for such a fantastic framework which allowed us to build both a local and Serverless AI server.
Adds the open-source web AI framework [BaseAI.dev](https://BaseAI.dev) as we're using Hono and Cloudflare heavily.
Asked @yusukebe before opening this PR.
P.S. Also honored to be part [The story of web framework Hono, from the creator of Hono](https://blog.cloudflare.com/the-story-of-web-framework-hono-from-the-creator-of-hono/)
> docs(top): change in usages

- docs/getting-started/nodejs.md
> docs(nodejs): describe serve-static politely

- docs/middleware/third-party.md
Listed hono-geo-middleware - https://github.com/ktkongtong/hono-geo-middleware in the 3rd party middleware section
> Added hono-geo-middleware

- .vitepress/config.ts
> feat: added bluesky profile link

- .vitepress/config.ts
- examples/cbor.md
cf. https://github.com/honojs/hono/issues/3648
> feat: add CBOR response example

- .vitepress/config.ts
- examples/hono-openapi.md
> docs: added example for hono-openapi

- docs/getting-started/ali-function-compute.md
This guide uses [rwv/hono-alibaba-cloud-fc3-adapter](https://github.com/rwv/hono-alibaba-cloud-fc3-adapter).
Fix https://github.com/honojs/hono/pull/3641
> docs: update Alibaba Cloud Function Compute getting started guide

- docs/getting-started/bun.md
- docs/getting-started/cloudflare-pages.md
- docs/getting-started/cloudflare-workers.md
- docs/getting-started/fastly.md
- docs/getting-started/netlify.md
- docs/getting-started/nodejs.md
- docs/getting-started/vercel.md
> docs: use `bun create` instead of `bunx create-hono`

- docs/middleware/builtin/cors.md
Explain that CORS should be called before the route is called
> Update cors.md to explain that CORS needs to be called before the route

- docs/guides/jsx-dom.md
it says this on the jsx page but not on this page
> add deno specifier to jsx dome page.md

- package.json
> fix: make Algolia search works

- docs/api/context.md
It would be useful to have this flow line.
> chore: add link to HonoRequest on Context

- docs/index.md
@rts-rob propsing adding Workers KV to 'who is using hono' doc
> Add Workers KV to who is using hono doc

- docs/index.md
> Fix capitalization

- docs/getting-started/cloudflare-workers.md
- docs/getting-started/vercel.md
- GitHub Action -> GitHub Actions
- cloudflare page -> Cloudflare Pages
- cloudflare worker -> Cloudflare Workers
- Github -> GitHub
- Page Router -> Pages Router
- node.js -> Node.js
> fix: wrong product name

- examples/proxy.md
> chore: Added note about new Proxy Helper in proxy.md

- docs/guides/jsx.md
Just a minor info to JSX page.
> fix(docs): Add note about .tsx extension requirement for JSX.

- docs/guides/rpc.md
source: https://github.com/honojs/website/pull/422#issuecomment-2213968727
> Upload File Note

- docs/helpers/cookie.md
The documentation around cookies is a little bit confusing, it took me a while to understand where each parameter goes, and where are actually the secrets.
This PR aims to make the doc a bit less fun, but more straightforward
> Update cookie examples

- docs/guides/testing.md
> docs(testing): include Vitest and Cloudflare recommendations

- docs/getting-started/fastly.md
Related: https://github.com/honojs/starter/pull/83
- Fix pnpm command
- Update Fastly Compute description
- Remove instruction for installing Fastly/CLI
- Include the CLI to the starter
> docs: update fastly

- docs/guides/middleware.md
This pull request provides the link to third-party middleware in guides/middleware section.
> Added link to third-party middleware

- docs/helpers/testing.md
Trying to help new users of Hono testing
https://github.com/honojs/hono/issues/4050#issuecomment-2776040574
> Update docs to be explicit about chaining

- .vitepress/theme/custom.css
Fix the search button styling on mobile, here is how it looks like:
> fix search button styling

- docs/guides/validation.md
> docs(guides/validation): add `new` for `HTTPException`

- docs/guides/rpc.md
Hello!
I finished writing up the documentation for issue https://github.com/honojs/hono/issues/4023 .
It's focused on routing with slashes, and I've added a NOTE about it not being encoded.
> Add usage of params with slashes in hc

- examples/hono-openapi.md
resolves https://github.com/honojs/website/issues/645
> docs: delete @scalar/hono-api-reference

- .vitepress/config.ts
- docs/getting-started/google-cloud-run.md
Drafted a Getting Started guide for Hono on Google Cloud Run.
> add google cloud run guide

- docs/getting-started/aws-lambda.md
run `cdk init app -l typescript` now, generated starter template is below.
File name and class name are changed, so I fixed these which are appeared in Hono document.
> Follow the latest AWS Lambda Starter Template

- docs/getting-started/nodejs.md
Removing instructions that are no longer required as a result of https://github.com/honojs/starter/pull/93
> nodejs docs updated to align with starter changes

- docs/api/request.md
Just making it more clear it is not just for files but also for input fields that has the same name :)
> Update request.md with examples parsing with same names

- docs/middleware/builtin/cors.md
Hi!
We had the following discussion on the main hono repo: https://github.com/honojs/hono/issues/4184, this is the associated PR. 
Let me know if it requires more information! Thanks! 🙏
> Add CORS usage with Vite

- .vitepress/config.ts
- docs/middleware/third-party.md
- examples/scalar.md
Related https://github.com/honojs/website/issues/645
Related https://github.com/honojs/website/pull/646
> docs: add Scalar back to examples

- docs/getting-started/vercel.md
- package.json
Hi! We've updated our support for Hono so that it can be used without any configuration required. These docs can now be updated for better DX.
Thanks!
> Update Vercel documentation.

- .vitepress/config.ts
- examples/behind-reverse-proxy.md
Related to https://github.com/honojs/node-server/issues/146#issuecomment-3153435672
> docs: add "Behind a reverse proxy" to examples

- examples/hono-openapi.md
> fix: updated hono-openapi docs for v1

- docs/guides/best-practices.md
Docs: refactor import to use AppType for client typing
> docs: refactor import to use AppType for client typing
