- content/docs/api/hono.md
Corrected 'RegExpRouter' spelling in '/content/docs/api/hono.md'
> Corrected RegExpRouter spelling

- content/docs/builtin-middleware/jsx.md
Documentation: replaced inadequate use of "memorize" with "memoize"
> docs: corrected typo in builtin-middleware page

- content/docs/getting-started/cloudflare-workers.md
`Env` should be passed as `{ Bindings: Env }`, otherwise the following ts error would occur:
> Pass Env as Bindings

- content/docs/builtin-middleware/cache.md
This PR adds mention of Cache middleware support in Deno 1.26+ and adds description of Cache middleware options.
> docs(cache): cache middleware for Deno, describe cache options

- content/docs/builtin-middleware/compress.md
This PR updates the page for the Compress middleware, adding descriptions of the options and clarifying a little about how encodings are selected for a response to the client.
> docs(compress): add options for compress middleware

- content/docs/builtin-middleware/basic-auth.md
- content/docs/builtin-middleware/bearer-auth.md
- content/docs/builtin-middleware/cache.md
- content/docs/third-party-middleware/_index.md
This PR describes the Basic Auth middleware, and also fixes a few mistakes in some other pages, such as removing the deprecated 3rd party validator middleware from the list.
It also updates the types for the Bearer Auth middleware and makes the Bearer Auth `Using on Fastly Compute@Edge` recipe match the improved description from the new Basic Auth page.
> docs(basic-auth): describe options, add recipes for multi-user auth

- content/docs/getting-started/cloudflare-workers.md
because the previous command `npx wrangler init -y` also creates package.json. This pull request closes #23.
> Remove `npm init -y` from "Cloudflare Workers"

- config.toml
- content/_index.md
- content/docs/api/hono.md
- content/docs/builtin-middleware/cache.md
- content/docs/builtin-middleware/compress.md
- content/docs/builtin-middleware/serve-static.md
- content/docs/getting-started/_index.md
- content/docs/getting-started/lagon.md
- content/docs/getting-started/others.md
- content/menu/index.md
Hi! As discussed in https://github.com/honojs/hono/issues/734, this PR adds documentation for Lagon.
I haven't included that the ETag middleware isn't working yet because it will be fixed really soon.
Edit: ETag middleware will work in the next release of `@lagon/runtime`, see https://github.com/lagonapp/lagon/pull/405
> docs: add Lagon docs

- content/docs/api/middleware.md
> fix middleware registration method

- content/docs/builtin-middleware/basic-auth.md
- content/docs/builtin-middleware/bearer-auth.md
See https://github.com/honojs/hono/discussions/793 for context. :)
> Added route+HTTP method examples for basic auth and bearer auth to restrict only certain operations.

- .vitepress/theme/custom.css
Hello 👋 congrats on V3 launch 
This or fixes a small thing, as you can see below color contrast for `code`  blocks on dark mode 
And here is the final look after adding the fix
> chore: fixing code color contrast on dark mode

- .vitepress/config.js
Currently, the link of **Edit this page on GitHub** points to the wrong endpoint (missing slash between main and file name), this PR fixes the config in `.vitepress/config.js` to point a correct endpoint.
https://user-images.githubusercontent.com/35027979/220932978-705078cc-c7de-43c3-9b92-6cb168f3c083.mp4
> fix: link to edit page

- guides/rpc.md
When passing the custom fetch method for a Cloudflare Service binding, it is necessary to use `bind` since without it an `Illegal Innvocation` Error is thrown.
> fix: Use `bind` with custom fetch method

- api/context.md
> Cloudflare Typo fix

- getting-started/bun.md
Unless the user remembers to cd into the `src` folder, executing the 4th command in the instructions will result in a `error: missing script "index.ts"` since the user is in the wrong path.
Minor fix, but makes the experience for first timers a little bit more straightforward & less error-prone :)
> Update: 4th step path to index.ts

- guides/examples.md
It appears the above example did not work until changing the interface for Bindings into a Type instead.
> Changed Interface to Type

- getting-started/deno.md
I think it's better to use `deno.land/x/hono` on Deno because `npm:` can't move on Deno Deploy now.
But is `deno.land/x/hono` unstable?
- Change `npm:` to `deno.land/x/hono`
- add missing codes
> Replace npm: to deno.land/x/hono

- middleware/builtin/cookie.md
After Hono `3.2.7` release, I've updated `cookie` docs with `deleteCookie`.
> Update cookie.md after Hono `3.2.7` release

- getting-started/bun.md
Use [`bun create`](https://bun.sh/docs/templates#bun-create) with the [hono template](https://github.com/bun-community/create-templates/tree/main/hono), because most people creating a project using bun will opt for the `bun` package manager over `npm`
> Opt for "bun create" in the bun guide

- getting-started/deno.md
the previously used import is deprecated
> Update assert link

- middleware/builtin/secure-headers.md
Currently the [Secure Headers page](https://hono.dev/middleware/builtin/secure-headers) contains some code examples that use `app.get` instead of correct method for the middleware — `.use`.
This PR replaces all `.get("*")` misuses with `.use("*")`.
> Fix: replace app.get with app.use in Secure Headers middleware

- middleware/builtin/jwt.md
Hi, @yusukebe 
I added this because when using the hono/jwt middleware, I didn't realize that payload was available until I went to the source code.
If you like it, I hope you'll MERGE it.
---
BTW, when using jwt on the edge, the only library I could find was https://github.com/tsndr/cloudflare-worker-jwt. are there any plans to release utils/jwt as a package like @hono/jwt?
> docs: Add usage of jwt with payload in hono/jwt middleware

- api/context.md
I couldn't find a place where I could elaborate on the `stream` argument.
Would this be ok?
> docs(context): add example for streamText() and stream()

- guides/helpers.md
In the helper guide there is a link to all the helpers, however, a few were missing due to recent updates
> docs: Add all helper links

- api/routing.md
This variant is more correct for routes which ends `.png`
> changed example for /api/routing#including-slashes

- guides/validation.md
Currently, the documentation doesn't mention anything about using multiple validators in the same request handler. Yet I've just found out that one can include multiple validators for validating different parts of a request. Moreover, typesafety will also work:
```ts
app.get("/:id",
zValidator("param", z.object({ id: z.string() })),
zValidator("json", z.object({ name: z.string() })),
//...
```
> feat(validation.md): add info about using multiple validators

- getting-started/vercel.md
The default Next.js app directory template is deprecated. If you use the currently provided code, you see this warning in the console:
```
⚠ Page config in /Users/anandchowdhary/Downloads/1q4/app/api/[...route]/route.ts is deprecated. Replace `export const config=…` with the following:
- `export const runtime = "edge"`
Visit https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config for more information.
```
It is recommended to change the following:
```ts
export const config = {
runtime: "edge",
};
```
to this:
```ts
export const config = {
runtime: "edge",
};
```
Relevant docs: [Route Segment Config](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config)
> docs(getting-started): Update Next.js runtime config export

- getting-started/deno.md
- index.md
`deno.land` redirect to `deno.com` in basically.
So I changed `deno.land` to `deno.com`.
And I changed the links to the correct docs.
> Fix Deno's links

- middleware/third-party.md
This PR adds [`@scalar/hono-api-reference`](https://github.com/scalar/scalar/tree/main/packages/hono-api-reference) to the list of third-party middleware.
The middleware takes an URL to a OpenAPI/Swagger spec and renders a beautiful API reference (like Swagger UI, but doesn’t look like it’s 2011).
It comes with a Hono custom theme and some other predefined themes:
**Example**
```ts
import { apiReference } from '@scalar/hono-api-reference'
// Create a Swagger file
app.doc('/swagger.json', {
info: {
title: 'Example',
description:
'The `@scalar/hono-api-reference` middleware renders a beautiful API reference based on your OpenAPI specification.',
version: 'v1',
},
openapi: '3.1.0',
})
// Load the middleware
app.get(
'/docs',
apiReference({
theme: 'purple',
spec: {
url: '/swagger.json',
}, …
```
> docs: add `@scalar/hono-api-reference` to list of third-party middleware

- api/context.md
- guides/jsx.md
Several methods in the Hono codebase are marked with the JSDoc annotation `@experimental`. However, there is no indication on the documentation website of which methods or features are experimental.
This pull request adds badges to feature sections that denote they are currently experimental.
> [!NOTE]
> It would probably be even better to include a note inside each section explaining the intent for if/when each API will stabilize, but I'm not familiar with the plan for these APIs so I didn't include notes like that.
> Add experimental badges

- middleware/builtin/bearer-auth.md
- Example now uses `app.on` to restrict by HTTP Methods
- Example route is now consistent with prior examples (`/api/page`)
> docs: improve the auth bearer multiple token example

- getting-started/nodejs.md
This PR adds a http2 section to the Node.js Guide.
> add node http2 instructions

- concepts/routers.md
- index.md
- top.md
Update `hono/tiny` size and the application size.
The app was created by `create-hono` command and replaced `hono` with `hono/tiny`.
https://github.com/honojs/hono/pull/1809
> update `hono/tiny` size

- middleware/builtin/cache.md
@yusukebe This pull request addresses issue #184, which is related to the Cache API not being supported on Deno Deploy. I have added a note to the documentation, clearly specifying that the Cache API is currently unsupported by Deno Deploy.
> Resolve Cache API Issue on Deno Deploy

- api/hono.md
The docs didn't clearly explain what the purpose of `app.fire()` was. This PR aims to fix that :)
> Clarify what app.fire() does

- getting-started/basic.md
Fix typo, your -> you in `getting-started/basic.md`
> Fix typo in basic.md

- guides/testing.md
I had a little bit of trouble getting a good testing setup for Hono + Cloudflare Workers, because they use so many `env` vars. I read this testing guide initially, but as it gave no hints to env, I tried a bunch of different solutions (even including some complicated Vitest code replacement) before I realized this was so easy to pull off.
Open to feedback/suggestions if there’s a better way to do this (i.e. if there’s a better recommended way), but I found this a relatively simple, flexible setup for my own testing.
> Add env section to testing guide

- getting-started/vercel.md
Noticed the example for the Next.js pages router used the app router syntax.
1. For edge functions in the page router, export a `config` variable, not `runtime` (https://vercel.com/docs/functions/edge-functions/edge-functions-api)
2. Route handlers are not supported in the pages router
> Fix next.js pages router example

- .vitepress/theme/custom.css
fix #197 
I add `--vp-c-orange-soft`(rgba(227, 96, 2, 0.1)) as theme color with high transparency.
And I set that to `--vp-c-brand-soft`.
https://hono.dev/middleware/builtin/jwt
> fix text and background are the same color in tip block section

- middleware/builtin/jsx-renderer.md
Hi, @yusukebe 
The type that was in the documentation could not support jsx that returned `Promise<string>`, so a type was added.
> docs: update custom context renderer type

- guides/rpc.md
Happy to change the wording, I had to dig around the debugging breakpoints to figure this out so thought it might be helpful to make it more clear.
> docs: update typo and add warning to `$url()` to use absolute URL

- middleware/third-party.md
@yusukebe  auth.js was missing in third party middleware  readme this pr adds that.
> Added auth.js in  third-party middlewares

- guides/rpc.md
As discussed in https://github.com/honojs/hono/issues/2120, use of the hono RPC client with larger applications isn't made clear by the existing documentations, so I've decided to append them with an explanation of the method recommended by @yusukebe in the aforementionned issue, using the "larger application" example from the best practices section of the docs.
> Document use of the RPC client in larger apps

- getting-started/nodejs.md
https://github.com/honojs/node-server/pull/129
> Add docs for Node.js adapter's new bindings

- helpers/css.md
It wasn't immediately clear how to style hover effects using Hono's `css` helper, but it's very possible - this adds the example to the documentation.
> docs: Mention nesting selector in css documentation

- getting-started/bun.md
- getting-started/cloudflare-workers.md
- getting-started/deno.md
- getting-started/nodejs.md
> [!CAUTION]
> `mimes` option for serve-static on Node.js has not been merged yet. 
> https://github.com/honojs/node-server/pull/135
> docs: add how to use `mimes` option for serve-static

- guides/rpc.md
Addresses #237, by updating the link to "Building a Larger Application" in the RPC section for Using with larger applications to point to: `/guides/best-practices#building-a-larger-application`
https://github.com/honojs/website/assets/43508242/c959c6c3-1f89-4ddc-a388-9712882be149
> docs: fix rpc building-a-larger-application link

- getting-started/cloudflare-workers.md
This PR adds a section in the Cloudflare Workers documentation on how to integrate a Hono app with other event handlers in a Module Worker.
This is based on @yusukebe's comment here: https://github.com/honojs/hono/issues/1720
I was looking to integrate a `scheduled` fn with my Hono app, and couldn't find anything in the docs for it. Hope this is useful!
> docs: Document integrating w/ other event handlers

- top.md
Polyfill.io server has moved to Rust, so Hono is no longer in use.
Ultra also hasn't been updated for about half a year.
Add OpenStatus instead. I think this is a good usage to use Bun as a platform.
> docs(top): change in usages

- concepts/stacks.md
"It is suitable for not just only returning JSON."
"not" was missing there. as i feel.
adding "not" strongly  emphasizes that Hono's capabilities extend beyond merely returning JSON.
> updated missing word "not"

- getting-started/cloudflare-pages.md
update the compatibility date. Ideally, this would be templated to always show today’s date.
> docs: Update cloudflare-pages.md

- getting-started/cloudflare-pages.md
I've noticed that the settings that include `name` and `compatibility_date` are not necessary for `wrangler.toml` for Cloudflare Pages. Because it is used only in development and we can set the compatibility date in a Dashboard.
> docs(pages): remove unnecessary settings in `wrangler.toml`

- getting-started/cloudflare-pages.md
- getting-started/cloudflare-workers.md
`pnpm deploy` is conflicting. Instead, do this: `pnpm run deploy`
```
$ pnpm deploy
ERR_PNPM_CANNOT_DEPLOY  A deploy is only possible from inside a workspace
```
https://pnpm.io/cli/deploy
> Fix pnpm deploy command

- helpers/jwt.md
This PR will add exp to JWT helper `sign()` example section. This will help users get clarity on how to implement other JWT claims.
[Add expires to JWT helper #2349](https://github.com/honojs/hono/issues/2349)
[Add IAT(issued at) and exp (expiration time)for jwt Tokens . #2407](https://github.com/honojs/hono/issues/2407)
> docs(jwt-helper): add exp to jwt sign example

- middleware/builtin/cache.md
This PR adds documentation for the `Vary` option in the cache middleware, which is scheduled for release in Hono version 4.2. For details on the implementation, please refer to [PR #2426](https://github.com/honojs/hono/pull/2426) on the Hono GitHub repository. 
|overview|only options|
|---|---|
|![localhost_5173_middleware_builtin_cache](https://github.com/honojs/website/assets/32933709/c90ff2fd-5684-4ea8-9b9c-0f061444d458)|![localhost_5173_middleware_builtin_cache (1)](https://github.com/honojs/website/assets/32933709/9ff374e4-6eda-4dde-925e-209502190f70)|
> chore: add vary header option to cache middleware docs

- middleware/builtin/trailing-slash.md
> fix(typo): misspelled `Trailing Slash`

- api/routing.md
When I migrated my app from Express to Hono, I needed this example.
```typescript
const book = express()
book.get('/book', ...)
book.post('/book', ...)
const user = express()
user.get('/user', ...)
user.post('/user', ...)
const app = user.use(book) // no base path needed
```
```typescript
const book = new Hono()
book.get('/book', ...)
book.post('/book', ...)
const user = new Hono()
user.get('/user', ...)
user.post('/user', ...)
const app = user.route('/', book)
```
> Add new grouping example

- getting-started/bun.md
- getting-started/deno.md
To maintain consistency with other examples that use `npm run dev` as the command for running an app, I've modified the run commands for Bun and Deno. Since the templates for Bun and Deno include the necessary scripts (https://github.com/honojs/starter/blob/main/templates/bun/package.json#L3, https://github.com/honojs/starter/blob/main/templates/deno/deno.json#L3), this should not cause any issues.
> Update Bun and Deno run commands

- getting-started/aws-lambda.md
- getting-started/basic.md
- getting-started/bun.md
- getting-started/cloudflare-pages.md
- getting-started/cloudflare-workers.md
- getting-started/deno.md
- getting-started/fastly.md
- getting-started/lambda-edge.md
- getting-started/netlify.md
- getting-started/nodejs.md
- getting-started/vercel.md
- guides/validation.md
- middleware/builtin/bearer-auth.md
- snippets/htmx.md
- top.md
Many command examples were syntax-highlighted as `txt`, so they have been changed to `sh`. Additionally, command examples that were not syntax-highlighted have also been updated to include `sh` highlighting.
| Before | After |
|--------|--------|
| <img width="702" alt="Screenshot 2024-04-07 at 1 22 49" src="https://github.com/honojs/website/assets/7889778/36b75d2a-3598-424f-8be6-e9d4ba8b28b3"> | <img width="701" alt="Screenshot 2024-04-07 at 1 23 07" src="https://github.com/honojs/website/assets/7889778/1cc2d5ee-614b-4ad4-adcc-a3631c6a20c6"> |
> Properly syntax highlight code blocks

- middleware/third-party.md
Auth providers like Auth0 prominently feature the term JWKS for their RSA JWT verification so it is good to include the term to make it easier to search for.
> Docs: clarified that RSA JWT uses JWKS

- getting-started/nodejs.md
The setup guide provided at https://hono.dev/getting-started/nodejs for Docker doesn't work.
- `npm create hono@latest my-app` Got `"@hono/node-server": "^1.9.0"` and `"hono": "^4.2.2"` in package.json
- `cd my-app`
- Created a Dockerfile according to the guide: https://hono.dev/getting-started/nodejs#dockerfile
- `docker build -t hono .`
- `docker run --rm -it --name hono -p 3000:3000 hono`
It should run the app in the container which can be accessed via http://localhost:3000.
```
(node:1) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/app/dist/index.js:1
import { serve } from '@hono/node-server';
^^^^^^
SyntaxError: Cannot use import statement outside a module
at …
```
> Include missing guide to make Docker work in Node.js

- getting-started/vercel.md
Hello, and thanks for Hono! I've made two changes to the Vercel docs:
1. I added a TS type to the exported `config` object that some of the API routes use
2. To address https://github.com/honojs/node-server/issues/84, I updated the pages router Node.js example to have the `bodyParser` setting turned off. Based on my manual testing, this issue only affects the pages router API routes running on Node.js: the app router as a whole and page router edge API routes are not affected and as such don't need bodyParser turned off.
> Update Vercel page

- guides/jsx.md
The basic JSX example was missing the default export so it would break on cloudflare workers if you copy/pasted that snippet.
> export default app to provide working basic jsx example for cf workers

- .vitepress/theme/custom.css
- index.md
this pull request updates the landing page copy of hono.dev.
a lot of people were asking in Hacker News "what does this do?" / "I can't tell what this is by the website".
the updates copy here re-focus hono in the lead title/subtitle as "Hono / Web application framework", with the perks being listed underneath in the paragraph.
the "View Docs" button text was updated to "Get Started". trying to guide people more to getting started as the immediate CTA button on the homepage.
> update landing page copy

- getting-started/fastly.md
The docs pointed to the Japanese version of the Fastly signup page. This commit updates the link to the generic signup page.
> Remove locale in Fastly link

- package.json
We had a section in our console that reported an error from vitepress, which has been [fixed](https://github.com/vuejs/vitepress/issues/3389), so I think we should update the version, currently vitepress is out of RC to release a stable version.
I've tested most of the pages locally and everything looks fine.
> chore: bump dependency vitepress to stable

- getting-started/bun.md
This has been a big question on Discord. Currently this is the only way I found to solve this issue. 
I understand if you do not want it added since it may not be the ideal way since the ip address is added to the env which is meant for environment variables.
> Add section on obtaining client IP address

- snippets/htmx.md
The current example for integrating `typed-html` with `hono/jsx` is outdated and doesn't work on current versions of both packages. I've updated the examples based on the instructions for [augmenting the JSX type definitions](https://github.com/Desdaemon/typed-htmx/blob/main/example/src/types.d.ts) for libraries which inject their own JSX types.
> Update htmx.md to add working instructions for using typed-htmx

- getting-started/bun.md
The reference to `index.ts` made it appear that the static folder was inside the `src` folder when root is set to `./`. Someone opened an issue thinking it was a bug [here](https://github.com/honojs/hono/issues/2565).
> Fix mistake in Bun serve static

- api/context.md
Sharing the Env types for making enables the `c.var` type-infer whether using the handler with no middleware or not.
https://github.com/honojs/hono/issues/2559
> docs: fix the type issue of `c.var`

- getting-started/nodejs.md
This issue was asked on `quick-questions` on Discord.
`mimes` option has not been added to `@hono/node-server` yet, so we will temporarily remove it from the documentation.
Ref: https://github.com/honojs/node-server/pull/135
> docs: remove mimes section in Node.js

- guides/rpc.md
I added "be" because "able" should be treated as an adjective.
> docs(rpc): Add "be" because it is missing.

- helpers/dev.md
Fix typo in `showRoutes` options at https://hono.dev/helpers/dev#options
> docs(dev): fix typo in showRoutes options

- .vitepress/config.ts
- getting-started/azure-functions.md
As mentioned on issue #346, I'm adding a getting started guide for running Hono on Azure Functions with [hono-azurefunc-adapter](https://github.com/Marplex/hono-azurefunc-adapter).
> Add getting started guide for Azure Functions

- middleware/builtin/cache.md
> docs(middleware): updated cache md

- middleware/builtin/body-limit.md
In reference to honojs/hono#2671,
Bun terminates requests above 128MiB by default. Setting the Hono `bodyLimit` middleware to a higher value will not help as the request is terminated before it even reaches Hono. Additionally, Bun does not provide an explicit error about this and the `onError` handler on Hono's `bodyLimit` middleware doesn't get called either, making errors hard to debug.
A section is added to warn users about this behavior with mitigation steps.
> add warning about Bun's default request body limit

- .vitepress/config.ts
- snippets/stripe-webhook.md
I added a page introducing how to create an API using Hono to handle Stripe Webhook events.
https://github.com/orgs/honojs/discussions/2518#discussioncomment-9170675
To add protection processing for the API endpoint, Stripe Webhooks require the raw request body. I created an article with sample code explaining how to obtain this for both Node.js and Cloudflare.
By adding this article, users using Stripe with Hono will find it easier to understand the integration method, and it will be easier to provide support in case of issues or discussions.
> docs[snippets]: add stripe webhook integration

- helpers/testing.md
Change '`testingClient()`' to '`testClient()`'
> docs(helpers/testing): fix typo

- snippets/stripe-webhook.md
I found unnecessary code in the Stripe webhook snippets.
We need to remove this line.
> Remove unnecessary code from the snippets

- middleware/builtin/cors.md
the `code-group` cause the rest of code blocks in the page can't work.
> fix: fix other code block can't display

- snippets/stripe-webhook.md
"Lear More" appears in heading on line 72.
> Typo on stripe-webhook.md

- getting-started/bun.md
This becomes unneeded with the new 4.4.0 update. I was considering adding the connInfo instead, but considering other pages, it would appear to just be duplicated content
> Remove IP Section in Bun

- getting-started/cloudflare-workers.md
Highlighted the information on module worker vs service worker regarding the local variables. The information wasn't highlighted so that new users of cloudflare worker runtime can find why their local environment variables aren't working.
> docs: improve cloudflare-workers page

- getting-started/cloudflare-workers.md
put module workers first since they're the recommended way 
move justification into the same paragraph to make sure it gets read
I had the same problem as [this commenter](https://github.com/honojs/hono/issues/194#issuecomment-2143549646). To me, this is clearer and points users more clearly to the happy path
> docs: reword cloudflare-workers section on service worker mode vs module worker mode

- getting-started/basic.md
A deprecated function is used in the example, this PR fixes it.
Ref: #391
> docs: use `upgradeWebSocket()` instead in adapter example

- getting-started/deno.md
- guides/middleware.md
- guides/others.md
Hono is no longer updated on deno.land/x, so change to JSR.
Since Deno also recommends JSR, use JSR instead of deno.land.
> docs: use JSR instead of deno.land/x

- .vitepress/theme/custom.css
The text color in light mode is pure black(`#000000`), which is not easy on the eyes.
Could you please make it the black color that is also used in [VitePress](https://vitepress.dev/)?
before:
after:
> docs: improve text color in light mode

- docs/helpers/websocket.md
I added a link, `@hono/node-ws` to WebSocket helper page.
Because I found people who think Hono doesn't provide WebSocket Adapter for Node.js.
> Add link to `@hono/node-ws`

- docs/getting-started/deno.md
In this PR, make it use `Deno.serve` instead of `export default` as an entry point of Deno. It can't get extra parameters from a Deno server with `export default`.
> use `Deno.serve` instead of `export default`

- docs/getting-started/aws-lambda.md
The Lambda example on the website uses a different property name than the ones actually provided at runtime (`context` vs. `lambdaContext`). 
This PR fixes the naming in the example, so it is obvious for new users.
> fix context naming in lambda example

- docs/index.md
Replace less common "adaptor" for a more common synonym "adapter"
> fix typo in index.md

- docs/index.md
Deno Docs has been moved to Lume, so Hono is no longer used.
https://github.com/denoland/deno-docs/pull/519
> remove Deno Docs from use-cases

- docs/middleware/builtin/compress.md
Add Deno Deploy to the list of services that already compress the body response.
See https://docs.deno.com/deploy/api/compression/
> Add Deno Deploy compresses the body response

- docs/getting-started/cloudflare-pages.md
- docs/getting-started/nodejs.md
- docs/middleware/builtin/jwt.md
- examples/prisma.md
Explained here: https://github.com/openzipkin/docker-alpine/pull/40
> docs: replace libc6-compat by gcompat in Dockerfile

- examples/pylon.md
Added async await to `createPost` because the following error occured.
> Property '$createPost' does not exist on type `Promise<User>`.
> fix pylon example

- .vitepress/theme/custom.css
- docs/helpers/accepts.md
- docs/helpers/cookie.md
- docs/helpers/dev.md
- docs/helpers/jwt.md
- docs/middleware/builtin/basic-auth.md
- docs/middleware/builtin/bearer-auth.md
- docs/middleware/builtin/body-limit.md
- docs/middleware/builtin/cache.md
- docs/middleware/builtin/compress.md
- docs/middleware/builtin/cors.md
- docs/middleware/builtin/csrf.md
- docs/middleware/builtin/etag.md
- docs/middleware/builtin/ip-restriction.md
- docs/middleware/builtin/jsx-renderer.md
- docs/middleware/builtin/jwt.md
- docs/middleware/builtin/logger.md
- docs/middleware/builtin/method-override.md
- docs/middleware/builtin/pretty-json.md
- docs/middleware/builtin/request-id.md
- docs/middleware/builtin/timing.md
closes #403
I made a few changes from the design proposed in the issue.
I set types as a code block and placed either required or optional at the beginning.
Basically, types are expressed as blocks of code, so I think that's natural.
Light
Dark
If you have any opinions about the design, please feel free to comment.
> docs: improve options section

- docs/middleware/builtin/cors.md
close https://github.com/honojs/hono/issues/1133
IMO: Given that this insight can be leveraged with other middleware as well, it might be a good idea to include it on the [Middleware page](https://hono.dev/docs/guides/middleware) as well.
> docs(cors): add documentation for environment-dependent CORS configuration

- docs/getting-started/cloudflare-workers.md
I found that an example for `serveStatic` for cloudflare-workers does not exist in the honojs/examples repo, so I deleted this line.
```md
See [Example](https://github.com/honojs/examples/tree/main/serve-static).
```
> docs: remove an expired link of serveStatic example for cloudflare-workers

- docs/guides/testing.md
This adds a link to the test helper in the testing guide. I didn't find the helper until after using `app.request` for a few tests.
> Add link to test helper

- docs/guides/middleware.md
Spent an hour trying to figure this out, then found the answer buried in [this discussion](https://github.com/honojs/hono/issues/414#issuecomment-1800878459). Looks like there's still ongoing discussion re: the ergonomics of this, but I figured it'd be useful to surface the current method.
> docs(middleware): add instructions for extending context

- .vitepress/config.ts
- .vitepress/theme/index.js
- package.json
- pnpm-lock.yaml
This PR add [vitepress-plugin-group-icons](https://github.com/yuyinws/vitepress-plugin-group-icons) to enhance the readability for `code-group`:
> docs: add group icons plugin

- docs/middleware/builtin/cache.md
Add that cache middleware is can be used in Deno Deploy.
Ref: https://deno.com/blog/deploy-cache-api
In addition, the `Cache-Control` header is only respected by Cloudflare Workers, so state that.
> docs(cache): can be used with Deno Deploy

- docs/middleware/third-party.md
This PR includes the following categories for the page listing third-party middleware:  
-  Authentication  
-  Validators  
-  OpenAPI  
What can be discussed is the order of these categories; for now, it is organized by the number of entries in each category.
We can also add more categories, but I have not found any meaningful groups for the rest of the list.
> Add category for third-party middleware

- docs/middleware/builtin/secure-headers.md
https://github.com/honojs/hono/pull/3394/commits/5a25e33e93aa8d4d68d8fb7e1c8e866a06a9710b
https://github.com/honojs/hono/pull/3394
Added a note about new middleware features implemented in the above commits.
To be released at hono@4.6.0
> docs(middleware): add permission-policy option on security-header's page

- docs/guides/rpc.md
Added tips to improve IDE performance when using RPC
> Tips for rpc perf

- docs/api/request.md
Added warning about `c.req.header()` behavior.
ref: https://github.com/honojs/hono/issues/3416#issuecomment-2352328842
> add warning about record from c.req.header()

- docs/helpers/cookie.md
```js
// Cookie names prefixed with __Host- can be used only if they are set with the secure attribute, must have a path of / (meaning any path at the host)
// and must not have a Domain attribute.
```
> Hono is following the best practices. The cookie helper will throw an Error when parsing cookies under the following conditions:
> - The cookie name starts with __Host-, but path is not /.
> - The cookie name starts with __Host-, but domain is ~***not***~ set.
>  Fixed incorrect description of __Host- prefix in cookie.md

- .vitepress/config.ts
- docs/index.md
- index.md
In this PR, update our slogan. The old one had "ultrafast" in it. It's not doubt, but currently, we have to say "build on Web Standards" rather than "fast."
> docs: update the slogan

- docs/getting-started/cloudflare-workers.md
The Serve Static for Cloudflare Workers had been deprecated, and Cloudflare released the Static Assets feature:
https://developers.cloudflare.com/workers/static-assets/
We have to use it now.
> docs(getting-started): use Static Assets for Cloudflare Workers

- .vitepress/config.ts
- .vitepress/theme/index.js
- .vitepress/theme/index.ts
- docs/api/context.md
- docs/api/exception.md
- docs/api/hono.md
- docs/api/presets.md
- docs/api/request.md
- docs/api/routing.md
- docs/concepts/benchmarks.md
- docs/concepts/middleware.md
- docs/concepts/stacks.md
- docs/concepts/web-standard.md
- docs/index.md
- package.json
I added [Twoslash](https://shiki.matsu.io/packages/vitepress#twoslash) to show TypeScript types.
Documentation users can check type definitions on the website.
Docs includes ambiguous codes, it was difficult to write correct TypeScript code. So I couldn't cover all of pages, but I think it has value.
> feat: add Twoslash to show TypeScript types

- docs/middleware/builtin/jsx-renderer.md
Closes #513 
- Added the `RequestContext` provider to make the example more easy to understand by everyone.
> fix(jsx): updated useRequestContext example

- docs/getting-started/basic.md
Fixes #519
* Removed ambiguous and unnecessary parts.
* Added "html Helper".
> docs(guide-basic): clarity on `Return HTML`

- docs/middleware/third-party.md
- Listed Hono OpenAPI Lib - https://github.com/rhinobase/hono-openapi in the 3rd party middleware section
> Added hono-openapi

- docs/getting-started/vercel.md
This PR adds documentation for using Hono with Next.js Node.js runtime in App Router setup.
Changes:
- Add new section showing how to use Node.js runtime with App Router
- Reorganize the Node.js section to clearly separate App Router and Page Router implementations
- Document that App Router doesn't require @hono/node-server package
- Maintain existing Page Router implementation details
The App Router implementation is simpler as it only requires setting `runtime = 'nodejs'` without additional packages.
Closes #529
> docs(getting-started/vercel): add Node.js runtime usage for App Router

- docs/helpers/css.md
documents the following feature: honojs/hono#3694
> css helpers: example 'how to use css helpers in combination with 'Secure Headers' middleware (Content-Security-Policy & nonce attribute)

- docs/middleware/third-party.md
this middleware wraps hono's context api in a neat little package for dependency injection. I think this is a really good addition to the list of the linked 3rd party middlewares. I also discussed the addition with the author (see: https://github.com/maou-shonen/hono-simple-DI/issues/15).
> docs: add hono simple di

- docs/getting-started/basic.md
- docs/getting-started/cloudflare-pages.md
- docs/getting-started/cloudflare-workers.md
- docs/getting-started/deno.md
- docs/getting-started/fastly.md
- docs/getting-started/netlify.md
- docs/getting-started/nodejs.md
- docs/getting-started/vercel.md
- docs/index.md
A simplified command has appeared, so use that.
`deno run -A npm:create-hono` => `deno init --npm hono`
https://deno.com/blog/v2.1#deno-init---npm-vite
> docs: project creation with `deno init`

- docs/guides/validation.md
Added example when testing using app.request() which is what originally tripped me up.
This relates to the warning added here https://github.com/honojs/hono/pull/3707
> docs(validators): content-type is required on requests with json validators

- docs/guides/validation.md
This is a follow-up to https://github.com/honojs/website/pull/540
- Fixed a code typo that said `.get` instead of `.post`
- Updated wording about "warning" in anticipation of https://github.com/honojs/hono/pull/3707
- Reworded code block descriptors
> fixed a few typos

- docs/middleware/third-party.md
Highlighit.io recently built a custom Hono middleware that can be used to quickly configure Highlight to collect logs and traces from a Hono app. This PR adds a link to learn about it under the third-party middleware docs.
> Add Highlight.io to third-party integrations

- docs/getting-started/basic.md
Deno linter problem: 'c' is declared but its value is never read.
We fix this by not destructuring the context parameter. We could have instead prefixed it with an underscore, but since the purpose of this document is to remain simple and easy to consume, we preferred this approach. There might be some good reasons why this document would want to retain the context param, so feel free to close this if that's the case!
> Fix linter warning (Deno)

- docs/middleware/third-party.md
Added the event emitter middleware (https://github.com/honojs/middleware/tree/main/packages/event-emitter) to the third-party middleware list.
> docs(middleware): Add event emitter to third party middleware section

- docs/api/routing.md
From what I understand, param regexes are always anchored. As such the second example is misleading as it implies the opposite.
> Remove boundary assertion from regex example

- docs/guides/rpc.md
Add information about using Hono RPC in projects where the client and server are in a single project. I spent way too much time wrestling with this before finding a comment online about the Hono version.
> docs: (RPC) add info about matching hono versions client-server

- examples/prisma.md
Fixes a link under the D1 Database section in `examples/prisma.md`
> Fix: Link Typo in prisma.md - D1 Database

- docs/middleware/builtin/compress.md
Add `options.threshold` to the documentation as it is already implemented.
> docs(middleware/compress): Add a compress middleware option

- docs/helpers/factory.md
The `@experimental` of createApp has already been removed, so I remove experimental from the document.
https://github.com/honojs/hono/pull/3164
> docs(factory): remove experimental from createApp

- examples/prisma.md
This PR fixes a typo in the documentation, correcting "Client Thunder" to "Thunder Client" which is the correct extension name. Also added some punctuation to improve sentence readability.
The previous sentence was:
> This will return all users in route `/`  using Postman or Client Thunder  to see the result.
The updated sentence is:
> This will return all users in the `/` route, using Postman or Thunder Client to see the result.
> Fix typo and improve sentence clarity in documentation

- docs/middleware/builtin/bearer-auth.md
This PR adds some helpful documentation alerting users to the fact that tokens cannot contain arbitrary characters. They must match the regex `TOKEN_STRINGS` defined in the hono codebase, otherwise a 400 error is returned indicating an invalid request.
> Clarify allowed token format to avoid surprises

- docs/middleware/third-party.md
I fixed tirhd party page Scalar API Refrence link broken.
**Target page**
https://hono.dev/docs/middleware/third-party
This link is broken.
https://github.com/scalar/scalar/tree/main/packages/hono-api-reference
> chore(middleware): fix Scalar API Refrence 404 not found

- .vitepress/config.ts
- docs/index.md
- docs/middleware/builtin/language.md
- Added new middleware `language.md` documentation
- Included code examples for common use cases
- Added detailed options reference tables
- Documented default configuration values
This update should be merged after [PR #3787](https://github.com/honojs/hono/pull/3787), which introduces the Language Middleware.
> docs: add language middleware documentation

- .vitepress/config.ts
Set the same `link` setting as the others.
It could be the cause of some kind of error?
Example:
> Normalize links (removing .md extension)

- public/images/logo.svg
- Reduced file size from 1740KB to 418KB while maintaining visual identity
- Improves website load time and reduces bandwidth usage for visitors
- Based on @qrg’s work in the now-closed issue: https://github.com/honojs/website/issues/574
- Made minor shape and color adjustments (before/after comparisons available in reference assets)
- Reference assets: https://github.com/tksh/optimize-hono-svg-logo
> Optimize SVG logo to reduce file size by 76%

- docs/concepts/stacks.md
Fixed compatibility with the latest version of the tanstack/react-query package.
https://tanstack.com/query/latest/docs/framework/react/guides/migrating-to-v5
https://tanstack.com/query/latest/docs/framework/react/reference/useMutation
> docs(concepts): fix tanstack/react-query example

- docs/concepts/stacks.md
- docs/getting-started/nodejs.md
- docs/guides/middleware.md
- docs/guides/rpc.md
Made a few additions based on questions I've seen come up frequently on Discord. More can probably be done, but I wanted to keep changes contained. Let me know if I should have created an issue or something instead.
Added some details about RPC inference and chaining. In my opinion, the examples are a little confusing because they use `const route` for the RPC typing (which isn't really explained). I actually missed that the first time I read through, and initially thought the examples were actually breaking.
- https://discord.com/channels/1011308539819597844/1346424853196050472/1346438748342190141
```typescript
const app = new Hono()
// directly chaining here, and using `typeof app`,  
// seems more consistent w other Hono docs, and
// how many devs architect apps
const route = …
```
> docs: add some details to address common questions

- docs/middleware/third-party.md
[Apitally](https://apitally.io/hono) is an API monitoring, analytics and request logging tool that includes a custom middleware for Hono in their SDK.
This PR adds a link to the [setup guide for Hono](https://docs.apitally.io/frameworks/hono) in the Apitally Docs that explains how to install and configure the middleware.
> Add Apitally to third-party middleware page

- docs/getting-started/nodejs.md
I've never heard of HTTP(S) requests being referred to as "access".
Also, "If access comes in and returns a file, write this code" sounds like the "access" is already returning a file, before you've written any code. I rephrased it as "and you want to return a file", so we're talking about the developer's intent, not something that is already happening.
> Tweaked wording in Node.js documentation

- docs/api/routing.md
The current sample code for host-header-based path routing (["Routing with host Header value"](https://hono.dev/docs/api/routing#routing-with-host-header-value)) does not replace query params, which leads to surprising (probably unintended?) behavior: QPs end up in the routed path, which means adding any query param breaks routing for that endpoint.
This fixes the regexp to make it more like the ["Routing with hostname"](https://hono.dev/docs/api/routing#routing-with-hostname) example that excludes QPs from the path.
> Add missing .* in Host routing example to avoid query params in routed path

- docs/guides/jsx.md
Fix typo in the example command.
> fix(docs): correct typo in JSX usage instructions

- docs/getting-started/aws-lambda.md
Added missing export keyword for the "Lambda response streaming" section. AWS Lambda function will throw an error if the handler is not exported
> fix: added missing export keyword

- docs/guides/rpc.md
Modified `import` to [*Type-Only Imports*](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) explicitly.
```ts
// from
import { AppType } from '.'
// to
import type { AppType } from '.'
```
In most cases, its difference is not a problem.
If compiler option [`verbatimModuleSyntax`](https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax) is enabled, type import must be written as follows:
```ts
// A. NG
import { AppType } from '.'
// B. OK
import type { AppType } from '.'
// C. it is also OK
import { type AppType } from '.'
```
However, in pattern C, **server-side code may be mixed into client-side** .
It is caused by rewriting rule of TypeScript.
The statement `import { type AppType } from '@/module'` is rewritten into …
> fix(docs): modify import statement to type-only imports explicitly

- docs/guides/jsx-dom.md
I have added a note on the following page about how to configure `hono/jsx/dom` using the esbuild options in `vite.config.ts`.
https://hono.dev/docs/guides/jsx-dom
I would appreciate it if necessary.
Thank you in advance.
> docs: add alternative JSX import source configuration for Vite

- docs/helpers/websocket.md
is there a reason why dangerouslySetInnerHTML is used here?
I think the formatting and neatness is improved by using the html helper
> docs: use `html` helper instead of dangerouslySetInnerHTML

- docs/guides/middleware.md
This is something that caused a lot of confusion when I was getting onboarded onto a hono-based project recently. It feels like it is worth calling out explicitly.
This is also a perfect opportunity for me to check for more holes in my understanding. Is what I've written correct, or is there a better mental model that I should be using instead?
> mention exceptions in the execution order section

- docs/guides/rpc.md
The documentation was not very clear on how to include cookies with every request. 
It took me a while to figure it out.
I hope adding this to the documentation saves another developer a headache.
> Docs: Add clear documentation for making the client send cookies with every request

- docs/guides/rpc.md
Fixed a syntax error in the RPC guide where the credentials key in the client configuration example had incorrect quotation marks.
> docs: fix typo in RPC client credentials example

- docs/getting-started/nodejs.md
> docs: use `node:22-alpine` on `docs/getting-started/nodejs`

- docs/getting-started/cloudflare-pages.md
- Add missing 'basePath' in the example provided.
The example clearly states the typical use-case of having the functions under the `/api` route, however if you do that, you'll need to add `.basePath("/api");` to the `new Hono` instruction.
> Update cloudflare-pages.md - Add missing basePath method

- docs/concepts/benchmarks.md
- docs/concepts/middleware.md
- docs/concepts/routers.md
- docs/concepts/stacks.md
- docs/guides/rpc.md
- docs/helpers/css.md
- docs/index.md
- docs/middleware/builtin/timing.md
- examples/pylon.md
- index.md
This pull request adds proper alt text to several images, while removing alt text from all images where the alt text is simply the filename/other nondescript values. 
This should make it easier to find when alt text was omitted.
I currently don't have the time to write alt text for images, but this should be a good base.
It should also be noted that it is reccomended to avoid images which just show text, for example: the code block in /index.md or the benchmarks in /docs/concepts/benchmarks.md
> Improve alt text.

- .vitepress/config.ts
- examples/better-auth-on-cloudflare.md
> I’ve closed the previous PR and opened a new one with the same changes, but with a cleaner commit history.
An example Hono application demonstrating Better Auth integration, optimized for deployment on Cloudflare Workers.
> Docs(example): add better-auth-on-cloudflare

- examples/better-auth-on-cloudflare.md
🙏 I mistakenly assumed that Hono supports the /** pattern because I saw it used in other documentation I was referencing.
To avoid confusion, I’ve updated the guide accordingly.
> docs(example): fix route wildcard from '/api/**' to '/api/*'

- docs/helpers/testing.md
It was unclear how to overwrite the `body` of a `testClient` request since the `testing.md` page only included `GET` examples. This example would have been useful when I was writing tests for `POST` requests in my own project.
> Add body example to testClient description

- docs/middleware/builtin/jwt.md
Add documentation for custom header location feature in JWT middleware.
> docs(v4.8): add headerName option to JWT middleware

- docs/middleware/builtin/cors.md
Add documentation for function-based allowMethods in CORS middleware, enabling dynamic method restrictions based on origin.
> docs(v4.8): add function support to CORS allowMethods

- docs/api/hono.md
- docs/getting-started/service-worker.md
Add documentation for the new fire() function from hono/service-worker and deprecate app.fire() with migration instructions.
> docs(v4.8): add fire() function and deprecate app.fire()

- docs/getting-started/nodejs.md
Remove a `+` that might have been a typo
Update the quotes to be single quotes similar to the rest of this doc.
> docs: fix typos in node.js docs

- .vitepress/config.ts
- docs/guides/rpc.md
- examples/hono-docs.md
This tool generates OpenAPI 3.0 specs and TypeScript type snapshots from Hono route definitions using AppType, improving DX.
> docs: add @rcmade/hono-docs to RPC guide

- docs/getting-started/fastly.md
Related to https://github.com/honojs/starter/pull/102
> docs(fastly): use `fire()` from `hono/service-worker` instead of `app.fire()`

- docs/guides/validation.md
This updates the “With Zod” examples to use:
```ts
import * as z from "zod"
```
Named import `import { z } from "zod"` has produced real-world failures in some stacks and TS/bundler configurations, e.g.:
* **TypeScript error:** “Module '"zod"' has no exported member 'z'.” (common when module resolution settings don’t line up).
[[colinhacks/zod#3739](https://github.com/colinhacks/zod/issues/3739)](https://github.com/colinhacks/zod/issues/3739)
* **Webpack/bundler error:** “export 'z' (imported as 'z') was not found in 'zod' (module has no exports)” — workarounds exist, but the namespace form avoids the pitfall.
[[colinhacks/zod#2085](https://github.com/colinhacks/zod/issues/2085)](https://github.com/colinhacks/zod/issues/2085)
* **Recent bundlers (Turbopack/Vite) regressions:** reports …
> docs(validation): use `import * as z from 'zod'` for broader toolchain

- docs/guides/rpc.md
Fixed incorrect type reference in the RPC documentation's client example.
- Changed `typeof routes` to `typeof app` in the Client type definition to match the correct variable name used in the example
The example was using `app` variable but the type was referencing non-existent `routes` variable, which would cause TypeScript errors when users copy this code.
> docs(rpc): fix type reference in client example

- examples/better-auth-on-cloudflare.md
Added schema import to ensure better-auth recognizes the schema.
Otherwise you'll run into exception like below:
```
[BetterAuthError: [# Drizzle Adapter]: The model "user" was not found in the schema object. Please pass the schema directly to the adapter options.]
```
> doc fix: better-auth need drizzle schema

- docs/api/exception.md
- docs/api/hono.md
Questions have come in on the Discord server from users who interpreted the docs to mean that `HTTPException` *must* be used. There are also some implementation details and "gotchas" that the docs didn't cover.
- clarify that `HTTPException` is thrown by Hono ecosystem code, but that devs can throw it themselves
- specify why `HTTPException` might be used instead of other errors
- add context about response types and header behavior
- add call-out about custom response status
- add info about `onError` and `notFound` behavior in sub-routes
> docs: clarify `HTTPException` docs

- .vitepress/config.ts
- examples/hono-authjs.md
- Introduced a new example guide (`examples/hono-authjs.md`) with setup, installation, and usage instructions for Auth.js integration in Hono applications.
- Updated `.vitepress/config.ts` to include the new guide in the examples sidebar for better navigation.
This took a while but done
This is for issue number #580
> Add Hono Auth.js integration guide and sidebar entry
